CREATE TABLE [dbo].[Companies]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[Name] VARCHAR(50) NOT NULL,
	[Street] VARCHAR(100) NOT NULL,
	[City] VARCHAR(20) NOT NULL,
	[State] VARCHAR(20) NOT NULL,
	[ZipCode] VARCHAR(9) NOT NULL,
	[Phone] VARCHAR(20) NOT NULL,
	[Active] BIT NOT NULL,
	[CreatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
	[EditedOn] DATETIME NOT NULL DEFAULT(GETDATE())
)
