CREATE TABLE [dbo].[CustomerContacts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[FirstName] VARCHAR(50) NOT NULL,
	[LastName] VARCHAR(50) NOT NULL,
	[CustomerId] INT NOT NULL FOREIGN KEY REFERENCES Companies(Id),
	[Email] VARCHAR(50) NOT NULL,
	[Active] BIT NOT NULL,
	[CreatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
	[EditedOn] DATETIME NOT NULL DEFAULT(GETDATE())
)
