CREATE TABLE [dbo].[InvoiceDetails]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[PlaceId] INT NULL FOREIGN KEY REFERENCES Places(Id),
	[InvoiceId] INT NOT NULL FOREIGN KEY REFERENCES Invoices(Id),
	[Price] DECIMAL(9,3) NOT NULL,
	[Code] VARCHAR NULL,
	[Description] VARCHAR(100) NOT NULL,
	[IsExtraWork] BIT NOT NULL,
	[Active] BIT NOT NULL,
	[CreatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
	[EditedOn] DATETIME NOT NULL DEFAULT(GETDATE())
)
