CREATE TABLE [dbo].[Places]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[Name] VARCHAR(50) NOT NULL,
	[Code] VARCHAR(20)  NOT NULL,
	[Description] VARCHAR(100) NOT NULL,
	[Price] DECIMAL(9,2) NOT NULL,
	[CustomerId] INT NOT NULL,
	[Street] VARCHAR(100) NOT NULL,
	[City] VARCHAR(20) NOT NULL,
	[State] VARCHAR(20) NOT NULL,
	[ZipCode] VARCHAR(9) NOT NULL,
	[Phone] VARCHAR(9) NULL,
	[Latitude] DECIMAL(9,6) NULL,
	[Longitude] DECIMAL(9,6) NULL,
	[Active] BIT NOT NULL,
	[FinishDate] DATETIME NULL,
	[CreatedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
	[EditedOn] DATETIME NOT NULL DEFAULT(GETDATE())
)
